#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
# -*- coding: utf-8 -*-


import os

import argcomplete


from EdgeOS.CLI import CLIFactory

if __name__ == '__main__':


    parser = CLIFactory.get_parser()
    argcomplete.autocomplete(parser)
    args = parser.parse_args()
    args.func(args)